import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export default new Router({
    routes: [
        {
            path:'*',
            component:()=>import('./components/pageturn.vue'),
            redirect:'/TemplateAPI/pageturn',
            meta:{
            	state:'翻页插件'
            }
        },
        {
            path:'/TemplateAPI/pageturn',
            component:()=>import('./components/pageturn.vue'),
            meta:{
            	state:'翻页插件'
            }
        },
        {
            path:'/TemplateAPI/dropdown',
            component:()=>import('./components/dropdown.vue'),
            meta:{
            	state:'下拉插件'
            }
        },
        {
            path:'/TemplateAPI/loading',
            component:()=>import('./components/loading.vue'),
            meta:{
            	state:'下载中插件'
            }
        },
        {
            path:'/TemplateAPI/radio',
            component:()=>import('./components/radio.vue'),
            meta:{
            	state:'单选框插件'
            }
        },
        {
            path:'/TemplateAPI/checkbox',
            component:()=>import('./components/checkbox.vue'),
            meta:{
            	state:'多选框插件'
            }
        },
        {
            path:'/TemplateAPI/button',
            component:()=>import('./components/button.vue'),
            meta:{
            	state:'按钮插件'
            }
        },
        {
            path:'/TemplateAPI/input',
            component:()=>import('./components/input.vue'),
            meta:{
            	state:'输入框插件'
            }
        },
        {
            path:'/TemplateAPI/date',
            component:()=>import('./components/date.vue'),
            meta:{
            	state:'日期时间插件'
            }
        },
        {
            path:'/TemplateAPI/alert',
            component:()=>import('./components/alert.vue'),
            meta:{
            	state:'弹出框插件'
            }
        },
    ]
})
